abi/README.md
abi/aapcs64/README.md
abi/vfabia64/README.md

The links were specified using rST syntax instead of Markdown syntax.

[abi][readme] Fix links to issue tracker.

---

abi/aapcs64/aapcs64.rst

The AAPCS64 said that:
void f(int8x8_t)
should be mangled as:
_Z1fu10__Int8x8_t
(with a 'u', using the namespace for vendor extensions).  But both
GCC and clang mangle it as:
_Z1f10__Int8x8_t
(without the 'u').  What clang and GCC do is now the de factor ABI
for many platforms, so this patch adds it as an allowable variation.
(We shouldn't just change the base ABI, since that would be unfair on
anyone who has implemented the original specification correctly for
their platform.)

Update C++ mangling to reflect existing practice

---

abi/aapcs64/aapcs64.rst

The text describing the frame chain in the AAPCS64 was written before PAC was added to the architecture.  For security purposes, when PAC is enabled, the return addresses need to be signed, but the AAPCS does not state this.
If we lacked such a requirement then the frame records would potentially contain a set of addresses that were unverifiable for the purposes of security and might be exploitable in terms of forming a ROP attack.
Code reading the frame chain obviously also has to be aware of this and deliberately strip the encoding in order to identify the real return address (it generally will not be able to unsign the address as the seed – the SP value – needed for this is not recorded in the frame).

clarify frame chain behaviour when PAC is enabled

---

abi/aapcs64/aapcs64.rst

Without this the final code block didn't display properly.

Code block formatting fixes

---

abi/vfabia64/vfabia64.rst

The issue has been discussed in
https://github.com/ARM-software/software-standards/issues/2

[abi][vfabia64] Specify the value of inactive lanes in output.

---

aapcs64/aapcs64.rst

This patch imports the SVE parts of the AAPCS64 from:
https://developer.arm.com/docs/100986/0000
Most of the text is copied verbatim.  However, I took the opportunity
to replace the term "Scalable Vector Aggregate" with "Pure Scalable Type",
which includes individual predicates and vectors as well as aggregates.
This avoids having to refer to "Scalable Vector Types, Scalable Predicate
Types and Scalable Vector Aggregates" in various places.
I also tried to clarify exactly which composite types are pure
scalable types.

Extend the AAPCS64 to support SVE types and registers

---

aapcs64/aapcs64.rst

There are two salient points we need to ensure the stack conforms to:
1. There is a single "stack background tag" that is set on the unused
part of the stack.
2. All stack space that is not allocated at public interfaces must have
their tag set to that "stack background tag".
Note:
This second requirement implicitly means that landing pads may not
change the stack pointer before calling back into _Unwind_Resume
unless they handle setting the tags on the stack space that is now
below the stack pointer.

Add requirements for stack space with MTE tags.

---

aapcs64/aapcs64.rst

There are three new bits: AH, FIZ and NEP, in bits 0,1,2 respectively.
This change adds AH and FIZ to the list of bits that can be
dynamically modified on purpose (like rounding modes), and puts NEP
into a new category of 'must be 0'.
Rationale: NEP changes the _shape_ of the affected instructions, in the
sense that it makes them write different amounts of output, and depend
on different amounts of their input. So it's very unlikely that code
generation will be able to be NEP-agnostic: code written to assume
NEP=0 won't do anything useful if run with NEP=1 and vice versa.
But the other two flags change minor details of return values of
existing operations, and might be useful not only to code binary-
translated from an architecture with those details of behaviour, but
also to code …

Specify ABI handling for 8.7-A's new FPCR bits.

---

aadwarf64/aadwarf64.rst

PC was a resereved register because it is not directly accessible
on the architecture but in special cases it need to be restored
in alternative ways.

Add DWARD register 32/PC.

---

aapcs64/aapcs64.rst

The Parameter passing rules contains 3 tables containing rules for each
of the 3 stages. In the original word document there were instructions
on how to interpret the rules. These have been missed out in the .rst
document.
Add the text back from the word document verbatim.

[AAPCS64] Put back missing instructions on how to interpret the tables

---

aaelf64/aaelf64.rst

Fully quote the symbol `S` in the description.

Typo fix in definition of GTPREL expression

---

aapcs64/aapcs64.rst

Rule C.4 stated that the NSAA is rounded up to the maximum of 8 and
the natural alignment of the HFA.
The original intent, and the GCC implmentation limits the alignment to
16 as this is the maximum alignment requirement of an AArch64 instruction.
Change rule C.4 to make it explicit that the alignment of NSAA is 16-bytes.

[aapcs32] Clarify rule C.4 when there is an overaligned HFA

---

aadwarf32/aadwarf32.rst

A spurious entry for the TPIDRURO register was added to the
register number table in the document initially uploaded to github.

[DWARF32] Deleted duplicated TPIDRURO register number entry.

---

aapcs64/aapcs64.rst

The document is inconsistent about use of the mathematical char and the
C style <= and >=. Standardise on using mathematical chars when not in
source code.
No functional changes.

[aapcs64] Use unicode and ≤ and ≥ instead of <= and >= [NFC]

---

aadwarf32/aadwarf32.rst

Functions, compiled with Return Address Authentication will need to
keep a pointer authentication code, used to validate integrity of the
return address upon function exit. This patch defines a
pseudo-register `RA_AUTH_CODE`, which denotes the authentication
code. It is an unsigned integer with the same size as a
general-purpose register.
The intent is for producers to use that pseudo-register with the
ordinary CFI instructions DW_CFA_offset, DW_CFA_register, etc.
If the value of ``RA_AUTH_CODE`` is used to authenticate the return
address, the authentication shall use CFA as a modifier.
Change-Id: If285812db90eecc626c8c5acf43ac2d779c6a797

PACBTI-M unwinding for DWARF

---

aaelf64/aaelf64.rst

The Alpha PAuthABIELF64 defines a small number of static and dynamic
relocations in the private vendor experiment space. When an upstream
implementation lands we will want to use non-experimental codes.
Step 1 is to reserve a range of static and dynamic relocations in
AAELF64 so we can guarantee no clash with any relocations defined in
the PAuthABI. When PAuthABIELF64 gets to Release state then
relocations can be added to the AAELF64 and the reservation can be
removed.

[AAELF64] Reserve relocation codes for PAuthABIELF64

---

aaelf64-morello/aaelf64-morello.rst
tools/rst2pdf/rst2pdf-abi.style

1) Assign e_flags bit 16 (0x00010000) to identify CHERI purecap binaries.
2) Add platform agnostic CHERI Note Section to specify abi variant.

[aaelf64-morello] ELF markers to identify Morello purecap binaries

---

aaelf64/aaelf64.rst

This fixes what appears to be a typo in the "Overview of PLT entry code generation" section (currently 4.1.2.2).

aaelf64: Fix typo in description of PLT entry code generation

---

aaelf64-morello/aaelf64-morello.rst

Fix typo in description of GDAT(S+A) relocation operation.

aaelf64-morello: Minor typo fix

---

pauthabielf64/pauthabielf64.rst

A new program property GNU_PROPERTY_AARCH64_FEATURE_PAUTH in
section .note.gnu.property replaces the previous proposal of a
full section .note.AARCH64-PAUTH-ABI-tag. This is easier
to implement, at least in the Bionic dynamic linker: the property
(and the existing .note.gnu.property section) can be trivially
extracted from a DSO, and is already happening for other properties
(mainly GNU_PROPERTY_AARCH64_FEATURE_1_AND to check for BTI and
PAC-ret). In contrast, a new section would require traversing all
the sections in the ELF and checking for the section name, which is
more complicated to implement and possibly slower.

[PAuthABI] Use a program property to mark PAuth compatibility

---

aaelf64/aaelf64.rst

The description of the changes are below.
I believe there is only one modification that is not purely superficial (i.e. that can change how the document would be read).
That's the change of "until the relocation after has been resolved" to  "until after the relocation has been resolved".
I think that's a clearly correct change -- but calling it out as the main place for review.
Put code-quotes around S when used to represent the symbol address, and
A when used to represent an addend to a symbol.
Some spelling mistakes:
requried  -> required
presense  -> presence
mechinasm -> mechanism
Remove a double-space character.
Change
Addresses stored in the place of these relocations may not be used for
pointer comparison until the relocation after has been resolved.
To
Addresses stored in the …

Various typo fixes in aaelf64.rst

---

addenda32/addenda32.rst

Hi,
This change is adding new value for Tag_CPU_arch for addenda to ABI Armv9-A architecture.

Add new value to Tag_CPU_arch for Arm Architecture

---

aapcs64-morello/aapcs64-morello.rst

Prior to this change, the wording of rule C.8 didn't allow passing a capability
in C7 in the case where the NGRN is 7 (i.e. when C0 through C6 are already
allocated). This change relaxes the rule, instead of requiring that the size of
the argument be strictly less than 16 * (8 - NGRN), we only require it to be
less than or equal to this value, which I believe gives the intended behaviour.
We also take the opportunity to avoid using the "quad words" terminology which
can be considered ambiguous.

aapcs64-morello: Fix up rule C.8

---

aaelf64/aaelf64.rst

Users should not rely on this property to enquire about the status
of the protection of an ELF file. If it is present, then yes, the
file has been protected. If it is not present, it can still have
been protected to some extent.
The comment on Custom PLT protection has also been removed. This
protection is seen as a separate feature to PAC-ret, since you could
ask the linker to generate protected PLTs regardless of the presence
of PAC-ret.

Soft-deprecate GNU_PROPERTY_AARCH64_FEATURE_1_PAC

---

aadwarf64/aadwarf64.rst

DW_CFA_AARCH64_negate_ra_state depends on the previous state of the RA_SIGN_STATE
register which makes complex to handle in cases when the register is set by
DWARF expressions because expression are lasily evaulated in runtime.

Document a limitation of the DW_CFA_AARCH64_negate_ra_state.

---

tools/rst2pdf/generate-pdfs.sh

This reduces the pdf size by more than 2 times:
$ du -h pdfs*
3.2M    pdfs
7.5M    pdfs-old
This pull requests addresses/implements issue https://github.com/ARM-software/abi-aa/issues/119

compress when generating pdfs

---

aapcs32/aapcs32.rst
aapcs64/aapcs64.rst

In the bitfield section of these documents there is a mention of language
bindings, which is expounded upon in another section of those documents. To make
this clear and for quick referencing, links were added to the language binding
section.
This should address https://github.com/ARM-software/abi-aa/issues/126

for aapcs32 and aapcs64, link mention of language bindings

---

aaelf64/aaelf64.rst

These relocations are special since they are both dynamic and static
relocations.  At the start of the "Relocation" section (currently 5.7)
we state that "A well-formed executable file or dynamic shared object
has no static relocations after static linking".  At the moment there is
nothing in this document which mentions that the above relocations are
both dynamic and static, and hence it could be confusing to see such
relocations in an executable if just going based on the ABI
documentation.
This commit adds both relocations to the "Dynamic Relocations" table in
order to make the document self-consistent.  We also include a note
explaining that these relocations are special.
--- Explanation of some decisions:
In the dynamic relocations table I do not mention the ELF64 code for
ABS32 even …

Include the ABS64 and ABS32 relocations in Dynamic relocations

---

tools/common/check-rst-syntax.sh

The current version of rstcheck (i.e. the version that the github CI
uses) does not have an option `--ignore-language` but instead has
`--ignore-languages`.
Without this update to our rst syntax checking script the github CI
fails on every PR.
N.b. The `rstcheck` change was here https://github.com/rstcheck/rstcheck/pull/100
N.b. I don't really know how to run the github actions CI on a PR change.
Hoping that this PR triggers it ;-)
E.g. https://github.com/ARM-software/abi-aa/pull/155

Update rstcheck options for github CI

---

aaelf64/aaelf64.rst

Add PT_AARCH64_MEMTAG_MTE to the table of AARCH64 segment types and document
its purpose.

Document new PT_AARCH64_MEMTAG_MTE segment

---

sysvabi64/sysvabi64.rst

Replace the current placeholder chapter with information on:
* ELF
* GOT and PLT
* GNU Indirect Functions
* Relocation Read-Only
A lot of the information in the chapter is general information. Not
specific to AArch64. However it can be useful to put the AArch64
information in context in a single place.
Resolves https://github.com/ARM-software/abi-aa/issues/152

[sysvabi64] Add chapter on Program Loading and Dynamic Linking.

---

ehabi32/ehabi32.rst

In case of nested function, changes in the VSP value to be used as modifier for the Return Address Authentication.
@vhscampos

[ehabi32] PACBTI-M unwinding rule in case of nested functions

---

aadwarf64/aadwarf64.rst

SME adds the concept of “streaming mode”, which can be entered
using SMSTART and exited using SMSTOP.  The SME ABI requires
these changes in streaming mode to be naturally nested:
a function entered in streaming mode must return in streaming
mode, and a function entered in non-streaming mode must return
in non-streaming mode.
The vector length in streaming mode can be different from the vector
length in non-streaming mode.  As a consequence, it's possible for the
value of the DWARF VG pseudo register to change at an SMSTART and at
an SMSTOP.  Each such change in value could invalidate VG-based DWARF
expressions for functions further up the call stack.  For example,
if a function F1 spills an SVE register to the stack, the size of
its stack frame might depend on VG.  If F1 then calls a …

Describe changes to VG in aadwarf64

---

aapcs64/aapcs64.rst

The AAPCS64 uses “process” as a cover-all term for “thread
or process”:
The AAPCS64 applies to a single thread of execution or
process (hereafter referred to as a process).
However, SME adds a register called TPIDR2_EL0 that forms an
important part of the SME PCS.  The “T” in TPIDR2_EL0 stands
for “thread”, so it seemed incongruous to use “process” when
describing its role in the PCS.
This preliminary patch therefore tries to avoid treating
“thread” and “process” as synonymous.  Since the exact
nature of threads and processes depends on the platform,
the patch tries to give a flexible definition.
Two later parts of the PCS refer specifically to processes:
- “Universal stack constraints”, when describing the parts of stack
memory that can be safely accessed.  These restrictions apply to …

Use “thread” rather than “process”

---

aapcs64/aapcs64.rst

This patch adds support for SME (Scalable Matrix Extension).
At this stage it is still alpha quality.
The request also includes https://github.com/ARM-software/abi-aa/pull/122

Add alpha-level support for SME

---

sysvabi64/sysvabi64.rst

On AArch64 we define DT_PLTGOT to be the address of the .plt.got section.

[sysvabi64] Define the processor specific interpretation for DT_PLTGOT

---

aapcs32/aapcs32.rst

The alias `v6` was mistakenly in the `Special` column; I have moved it to `Synonym`. I have also included its other role in the `Role` column.

Fix formatting of v6 cell in core registers table

---

aapcs64/aapcs64.rst

This is a definition of a term in the Bit-field equations.  It is not quoted in the same way as other definitions, making it less obvious on reading.  This commit fixes that.

Add syntax around "current bit address" definition in aapcs64

---

vfabia64/vfabia64.rst

This is just a minor fix to replace a hardcoded section number with a link to what I believe was the intended section it was originally pointing to.

[vfabia64] Replace hardcoded section number with link

---

aaelf64/aaelf64.rst

Most relocations act on immediates of instructions and specify the bits of the calculated value that are put into that instruction.
The "Static Data relocations" table is for data relocations which do not act on instructions.  These seem to have not explicitly mentioned the number of bits written by the linker.  They also do not mention the alignment of the "place" that is written (something which is written in the aaelf32 document).
Here we mention both the above in the "Comment" field of the relocation tables.  This differs from where the aaelf32 document describes the size and alignment of static data simply because I felt this way would be easier to find the information and would follow the existing style in the document better.
Am happy to change that if requested.
N.b. I have not …

Mention size and alignment of "place" for some relocations

---

aadwarf32/aadwarf32.rst
aadwarf64-morello/aadwarf64-morello.rst
aapcs32/aapcs32.rst
bpabi32/bpabi32.rst
clibabi32/clibabi32.rst
ehabi32/ehabi32.rst
semihosting/semihosting.rst

Avoids a warnings when generating html, yet has no effect on the Github display or the PDF.
https://github.com/ARM-software/abi-aa/issues/207

Remove none from code-block:: in all rst documents

---

semihosting/semihosting.rst

In 32-bit semihosting, it was previously unclear whether a high-bit-set return value should be interpreted as a time before 1970 or after 2038. This change clarifies that it is the latter, which means that the semihosting API does not contain a year-2038 bug.
This is a safe change because SYS_TIME returns the _current_ time, and does not also need to deal with historic times (as the C <time.h> API does). Semihosting did not exist before 1970, so there will never have been any case in which SYS_TIME genuinely needed to return a value before 1970 as the current time.
The scope of this clarification is limited to the return value from SYS_TIME. It does not constrain the size of time_t used by C standard libraries, which are free to convert the unsigned 32-bit return value into a 64-bit …

[Semihosting] Specify SYS_TIME return value as unsigned.

---

pauthabielf64/pauthabielf64.rst

We need to pick two odd numbers for DT_AARCH64_AUTH_RELRSZ and DT_AARCH64_AUTH_RELRENT. The recent DT_AARCH64_MEMTAG_* tags have occupied a few numbers.
Let's use 0x70000011 to 0x70000013. The numbers are consecutive to be similar to DT_RELRSZ/DT_RELR/DT_RELRENT.

[PAuthABI] Change DT_AARCH64_AUTH_RELR* to avoid conflict with DT_AARCH64_VARIANT_PCS

---

memtagabielf64/memtagabielf64.rst

MEMTAG_STACK should be d_val (a bit to indicate that MTE stack is either on/off), and MEMTAG_GLOBALS should be d_ptr (a pointer offset to a section containing memtag globals descriptors).
This is the way that lld has implemented it, as it's the local semantics (`MEMTAG_GLOBALS` is a pointer-to-section that needs load bias adjustment, and `MEMTAG_STACK` is a single bit that enables `PROT_MTE` on the stack).
This unfortunatly does mean that we diverge from the accepted semantics of `odd == d_val`, and `even == d_ptr`, but this seems like the best trade-off as we've shipped a compiler that did the non-spec-but-more-logical thing and shipped binaries to end users. Much better than shipping a whole new set of `MEMTAG_GLOBALS_2` and `MEMTAG_STACK_2` to fix the mistake.
Found by eugenis@ in …

Change MEMTAG_STACK to be d_val, and MEMTAG_GLOBALS to be d_ptr

---

aaelf64/aaelf64.rst
sysvabi64/sysvabi64.rst

The Elf for the Arm 64-bit Architecture (aaelf64) describes the processor specific parts of the ELF specification common to all ELF environments from a statically linked freestanding environment with no OS to a hosted environment that supports dynamic linking.
The dynamic linking parts that are specific to SystemV style operating environments such as Linux, and in particular the GNU properties which are based on a Linux ABI extension are better documented in the SystemV ABI for Arm 64-bit Architecture.

[AAELF64][SYSVABI64] Move dynamic linking contents to sysvabi64

---

sysvabi64/sysvabi64.rst

Add GNU_PROPERTY_AARCH64_FEATURE_1_GCS to the GNU property GNU_PROPERTY_AARCH64_FEATURE_1_AND.
This permits executables and shared libraries to declare that they are compatible with GCS, this permits a platform to enable GCS for a program when the executable and all of its dependecies are compatible with it.
When GCS is enabled, use of dlopen of a shared library that is not GCS compatible is platform defined. Some platforms may be able to disable GCS, others may decide to refuse to load the library.

[SYSVABI64] Add Guarded Control Stack (GCS) Feature Bit

---

addenda32/addenda32.rst

Fix 'unit32' typo in addenda32.rst

---

aapcs64/aapcs64.rst

The SME and SME2 ABI have been implemented in upstream GCC and Clang/LLVM, so I think they're ready to be treated as Beta.

Promote the SME(2) ABI status from Alpha to Beta

---

aapcs64/aapcs64.rst

With the release of the Cortex-R82, we now have an AArch64 CPU which can be built without any floating-point instructions or registers, so I think we should re-consider our decision to not have a soft-float variant of the AArch64 PCS.
I've worded this as a variant over the base PCS, to keep it simple.
No compiler implements this yet, but clang does already allow passing floating-point types without an FPU, and seems to implement the first bullet point correctly. I'm working on LLVM patches which will implement bullet points 2 and 3.
GCC doesn't currently allow any use of floating-point types without an FPU for AArch64, so we don't need to worry about compatibility with existing code there.
For the fourth bullet point, I don't think we need to define the PCS for vector types, because these …

Define soft-float PCS for AArch64

---

aadwarf64/aadwarf64.rst

This introduces DWARF support to enable unwinders to authenticate return
addresses signed using FEAT_PAuth_LR, where the value of PC is used as
an extra diversifier.
To achieve that, this proposes the following changes to the aadwarf64
document:
* Expanding usage of the `RA_SIGN_STATE` pseudo-register, allocating
it's bit[1] to indicate wether the value of PC has been used for
return address signing.
* Introducing a new vendor call frame instruction,
`DW_CFA_AARCH64_negate_ra_state_with_pc`, which negates both bit[0]
and bit[1] of `RA_SIGN_STATE` and instructs the unwinder to capture
the current code location to be used when authenticating the return
address.
Co-authored-by: Oliver Stannard <oliver.stannard@arm.com>

[aadwarf64] Add DWARF support for unwinding with FEAT_PAuth_LR enabled

---

pauthabielf64/pauthabielf64.rst

Make the alternative .note.gnu.property section the default ELF marking scheme for ELF executables and shared libraries. Preserve the original SHT_NOTE section as an alternative for legacy compatibility.
Tighten up the wording to restrict the property to just a pair of 64-bit words. This permits the program property to be described by a pair of build attributes which Arm plans to introduce for relocatable ELF object marking.

[PAuthABIELF64] Use .note.gnu.property section as ELF marking scheme.

---

sysvabi64/sysvabi64.rst

The alpha ELF extension documents define dynamic tags. To avoid avoidable clashes with the main specification, mark the values used as reserved.

[AAELF64] Reserve dynamic tags used by memtagabielf64 and pauthabi64

---

aaelf64/aaelf64.rst
pauthabielf64/pauthabielf64.rst

Now that there will be a concrete implementation of PAuthABI in upstream LLVM we need to move the PAuthABI relocation codes out of the space reserved for private experiments to their final codes. These are in the range of codes already reserved for the PAuthABI in AAELF64.
The description of the operations will remain in the PAuthABI64 as this remains an extension.

[AAELF64][PAUTHABI64] Assign PAuthABI relocation codes.

---

clibabi32/clibabi32.rst

I just noticed a paragraph that was grammatically confusing because it contained a comma with no word before it, and an equality with no left-hand side.
It looks to me as if the <errno.h> macro name EDOM was accidentally deleted in both cases. (Rationale: EDOM is an error code closely related to ERANGE, and matches the claim in the paragraph that its consensus value is 33 – that's its value on Linux, for example.)
Searching for ERANGE in the rest of the document turned up another two places where there was a missing word that looked as if it ought to be "EDOM".
I've no idea how this happened! But it seems like an easy fix.

[CLIBABI32] Restore missing reference to EDOM.

---

aapcs64/aapcs64.rst

At least one community got confused as to whether it refered to the callee or the caller. Use subroutine instead of it to make it clear that we are referring to the same subroutine that takes z and p registers as arguments.
Fixes https://github.com/ARM-software/abi-aa/issues/266

[aapcs64] Clarify meaning of "it" when preserving z and p regs

---

pauthabielf64/pauthabielf64.rst

No implementation is using the alternative marking scheme; take the opportunity to remove it, so that toolchains do not need to support it.
The alternative marking scheme started as the default one back when the spec was written. At the time there were only prototype implementations for which signing schema compatibility and versioning weren't important.
Over time Arm's ELF marking for SysV has evolved such that the preference for ELF executables and shared-libraries is to use GNU Program Properties. We intend to migrate to Build Attributes for relocatable objects, but until that change is made GNU Program Properties should be used in relocatable objects too.
The alternative ELF marking scheme was preserved for backwards compatibility, however no current implementation needs that so it …

[PAUTHABIELF64] Remove alternative ELF marking scheme

---

pauthabielf64/pauthabielf64.rst

As pointed out in https://github.com/ARM-software/abi-aa/issues/253 the R_AARCH64_AUTH_GOT_LO12_NC is meant to be the AUTH variant of R_AARCH64_LD64_GOT_LO12_NC. As there is also a
R_AARCH64_LD32_GOT_LO12_NC relocation rename the relocation to R_AARCH64_LD64_AUTH_GOT_LO12_NC.
These relocations are in the appendix as we are currently expecting the GOT to be RELRO and unsigned in most signing schemas.

[pauthabielf64] Fix typo in relocation name

---

pauthabielf64/pauthabielf64.rst

With the tiny code model and a signed GOT, an adr instruction is needed to get the address of the GOT entry for input to the authenication. For example:
adr x8, :got_auth: symbol
ldr x0, [x8]
// Authenticate to get unsigned pointer
autia x0, x8
The adr requires a new relocation code where there isn't a direct equivalent in the main ABI as there is not need to take the address of the GOT slot when no authentication is required.
We define R_AARCH64_AUTH_GOT_ADR_PREL21_LO21 for this purpose following the naming convention of R_<CLS>_ADR_PREL_LO21. which is its closest equivalent.

[PAUTHABIELF64] Add R_AARCH64_AUTH_GOT_ADR_PREL_LO21 relocation

---

aaelf64/aaelf64.rst

This brings AAELF64 into line with AAELF32, which already has a similar clarification for the MOVW+MOVT pair. For the instructions which shift their operand left (ADRP, and the shifted MOVZ and MOVK), if the relocation addend is taken from the input value of the immediate field, it is not treated as shifted.
The rationale is that this allows a sequence of related instructions to consistently compute the same value (symbol + small offset), and cooperate to load that value into the target register, one small chunk at a time. For example, this would load `mySymbol + 0x123`:
mov  x0, #0x123          ; R_AARCH64_MOVW_UABS_G0_NC(mySymbol)
movk x0, #0x123, lsl #16 ; R_AARCH64_MOVW_UABS_G1_NC(mySymbol)
movk x0, #0x123, lsl #32 ; R_AARCH64_MOVW_UABS_G2_NC(mySymbol)
movk x0, #0x123, lsl #48 ; …

[AAELF64] Clarify how addends work in MOVZ, MOVK and ADRP.

---

aaelf64/aaelf64.rst
pauthabielf64/pauthabielf64.rst

The GDAT(S + A) relocation operation requires a static linker to create a GOT entry for (S + A). Requiring at least one GOT entry for each unique tuple (S, A). Unfortunately no known static linker has implemented this correctly, with one of two forms being implemented instead:
* GDAT(S) with the addend ignored.
* GDAT(S) + A with a single GOT entry per S, and A added to the value of GDAT(S). These implementations are correct and consistent only for an addend (A) of zero.
No known compiler uses non-zero addends in relocations that use the GDAT(S+A) operation, although it is possible to generate them using assembly language.
This change synchronizes the ABI with the behavior of existing static linker implementations. The benefit of permitting code generators [*] to use a non zero addend in …

[aaelf64][pauthabi64] Remove addend in GDAT relocation operation

---

aaelf64/aaelf64.rst

There is a typo in the spelling of R_<CLS_ABS64, it is missing a close angle brackets, and should be R_<CLS>_ABS64.
Similarly there should only be one entry in the dynamic relocation table, with R_<CLS>_ABS64 retaining the static relocation code but using the dynamic relocation semantics.
Added a clarifying line to state that the R_<CLS>_ABS64 is both a static and dynamic relocation.

[aaelf64] Fix PAuthABI relocation details.

---

.github/workflows/ci.yml

our GitHub action checks were failing because of update-artefact got depreciated.
While updating, I took the liberty to also update the other script versions:
- update checkout to v4, v2 is using a node that will soon be depreciated
- upload-artifact to v4, v2 has become depreciated
- update setup-python to v5, just to stay up-to-date

Actions version bump

---

tools/common/generate-release-links.sh

- removed referring to developer.arm.com, as we have moved all the legacy docs here now
- moved some docs into the 64-bit section

slightly tweak the release links generator script

---

sysvabi64/sysvabi64.rst

Add requirements for when a tool must generate a BTI instruction. This permits tools to elide BTI instructions when they can prove that no indirect branch to that location is possible from local information available to the tool.
Static linkers are not allowed to assume that all direct branch targets have a BTI instruction. If a veneer is required then the static linker must generate additional BTI instructions if needed.
A static linker is allowed to assume that a symbol that is exported to the dynamic symbol table has a BTI instruction.
In practice this will permit compilers to remove BTI instructions from static functions that do not have their address taken and that address escapes the function.
This matches the behavior of the GNU toolchain.
Fixes …

[sysvabi64] Document requirements for tools wrt BTI

---

sysvabi64/README.md

The first link in this document was referencing a non-existent file.

Fix link to sysvabi64

---

aapcs64/aapcs64.rst

This PR adds a new "agnostic-ZA" interface which is intended to be called from any subroutine without requiring a change to PSTATE.ZA. This PR also adds new SME ABI routines to save/restore state enabled by PSTATE.ZA.
The corresponding ACLE PR can be found [here](https://github.com/ARM-software/acle/pull/336).

[SME] Add agnostic-ZA interface and routines to save/restore SME state

---

dbgovl32/dbgovl32.rst
rtabi32/rtabi32.rst

I noticed one of these in passing in RTABI32: Github's Markdown renderer showed a spurious backtick at the end of a sensible identifier in fixed-pitch text. Looking at the source, that's because the fixed-pitch section was closed by three backticks instead of the usual two.
Grepping the rest of the repository turned up one more case of the same thing, in DBGOVL32. This patch fixes both.

Markup: fix two accidental triple-backticks.

---

pauthabielf64/pauthabielf64.rst

Add static Auth equivalents of the existing relocations:
* R_AARCH64_TLSDESC_ADR_PAGE21
* R_AARCH64_TLSDESC_LD64_LO12
* R_AARCH64_TLSDESC_ADD_LO12
These are sufficient to implement the small code-model for TLSDESC using the PAuthABI. Support for the tiny and large code-model is not implemented for the PAuthABI, or for the normal ABI in both clang and GCC so we defer from specifiying Auth variants of all possible relocations.
I've followed the convention that non-zero addends are not permitted for GOT generating relocations. As each unique S+A combination needs its own pair of GOT slots indexed by S+A and no static linker supports that.
Fixes https://github.com/ARM-software/abi-aa/issues/293

[pauthabi64] Add Auth variants of TLSDESC generating GOT relocations

---

aaelf64-morello/aaelf64-morello.rst

Fix the specification for `R_MORELLO_JUMP_SLOT` to use the same format as `R_MORELLO_RELATIVE`.

[Morello] Insufficient R_MORELLO_JUMP_SLOT documentation #69

---

sysvabi64/sysvabi64.rst

The aapcs64 base procedure call standard requires floating point and simd registers. With the advent of a soft-float ABI for R-profile CPUs without floating point, we are making it explicit that platforms based on the System V ABI are required to use the base procedure call standard.
Soft-float pull request in https://github.com/ARM-software/abi-aa/pull/232

[sysvabi] Make hard-float a requirement for sysvabi

---

atomicsabi64/atomicsabi64.rst

Add details of atomic floating-point operations for `fetch_add`, for 16-bit, 32-bit and 64-bit floating-point types. Not support for 8-bit and 128-bit types.

[LSFE] Update `fetch_add` to add atomic floating-point operations

---

aapcs64/aapcs64.rst

FP8 ABI have been implemented in upstream GCC and Clang/LLVM. They're ready to be treated as Beta.

Promote the FP8 ABI status from Alpha to Beta

---

.gitignore
CONTRIBUTING.md

Add instructions for how to build PDF files locally using Python virtual environment.
Also add a `.gitignore` file.

[CONTRIBUTING] Update instructions for how to build PDF files locally

---

aaelf64/aaelf64.rst

Range extension veneers in a bare-metal context must not assume a BTI instruction is at the destination.
There is documentation in sysvabi64 that states this, but strictly speaking this need not apply to a bare-metal context. Document that linker generated veneers cannot assume a BTI for definitions in the same link unit.
Bare-metal systems do not support PLT or iPLT (ifunc) so the requirements surrounding code-generation can stay in the sysvabi64.

[AAELF64] BTI and veneers for bare-metal contexts.

---

aapcs64/aapcs64.rst

Currently, it's not completely clear whether a struct containing a mixture of different 16-bit floating point types is a Homogeneous Aggregate or not:
struct foo {
__fp16 a;
__bf16 b;
};
I think that the best interpretation of the current text is that this is an HFA, because there is only one entry in the "Fundamental Data Types" table, which is the only thing considered in the definition of a Homogeneous Aggregate.
However, the table in the "Mapping of C & C++ built-in data types" section used the formats in a column which otherwise contains Fundamental Data Types, which could be read to imply that the above struct is _not_ an HFA. I don't think this is correct, so I've moved the formats to the notes column, making it clear that the two source types map to the same Fundamental Data Type. …

[AAPCS64] Clarify how __bf16 affects HFAs

---

aapcs64/aapcs64.rst

The ABI doesn't currently say anything about the first fault register (FFR). The de facto treatment is that there is no guarantee about the contents of the FFR across a public interface boundary, i.e. it is a temporary register (in the language of the PCS).  Document this.

[aapcs64] Document ABI stance on FFR

---

sysvabi64/sysvabi64.rst

An ifunc resolver function needs a BTI as it is called indirectly via the dynamic loader when resolving the R_AARCH64_IRELATIVE relocation. When static linking the relocation is also resolved via an indirect branch to the resolver from a local resolver function like _dl_relocate_static_pie in glibc.

[SYSVABI] Add example that ifunc resolvers are indirectly called

---

tools/rst2pdf/requirements.txt

rst2pdf is falling over in CI with:
"ModuleNotFoundError: No module named 'roman'"
explicitly add roman to rst2pdf requirements.txt

[CI] Add roman to rst2pdf requirements.txt

---

aaelf64/aaelf64.rst

The structure protection extension [1], introduces two new relocations:
R_AARCH64_PATCHINST which replaces an instruction with the result of the relocation if the referenced symbol is defined. The relocation is intended to implement deactivation symbols [2], which can be used to "undo" structure protection when it isn't safe to apply.
R_AARCH64_FUNCINIT64 generates a R_AARCH64_IRELATIVE relocation at the place. This is similar to R_AARCH64_ABS64 referencing a symbol of binding STB_GNU_UNIQUE, with the main difference being that R_AARCH64_FUNCINIT64 references non STB_GNU_UNIQUE symbols. The relocation is used to initialize function pointers in static structs at load time by calling the equivalent of an ifunc resolver function that returns the signed address.
[1] …

[AAELF64] Document structure protection relocations

---

sysvabi64/sysvabi64.rst

Documents the Application Binary Interface requirements for
Function Multi-versioning (FMV) on System V platforms.
A global variable `__aarch64_cpu_features` provided by
the runtime library contains information about the available
CPU features. The variable must be defined as DSO-local with
its symbol visibility set to `STV_HIDDEN`.
A function `__init_cpu_features_resolver` provided by
the runtime library is used for initializing the variable
`__aarch64_cpu_features`. The function must be defined as
DSO-local with its symbol visibility set to `STV_HIDDEN`.
Accessing `__aarch64_cpu_features` is reserved for the
compiler generated code or the runtime library. If the
variable is only accessed for FMV, then it may be placed
in the Relocation Read Only (RELRO) program segment to
prevent it …

[FMV][AArch64] Document the interface for Function Multi-versioning.

---

sysvabi64/sysvabi64.rst

The R_AARCH64_GOTPCREL32 relocation, currently used in clang when relative vtables are enabled, has a signed offset so is limited to 2 GiB range. This limits the range of GOT from the vtables to 2GiB.
Document this restriction in the tables for the small and medium code model. Add a note to explain the reason, so that if code generation does not use the relocation the distance to the GOT can be increased.
Fixes #343

[sysvabi64] Code Models. Limit range to GOT to 2GiB
